version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
      - image: circleci/mysql:5.7
    working_directory: /go/src/github.com/square/squalor
    steps:
      - checkout
      - run:
          name: Waiting for MySQL to be ready...
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run: go get -v -t -d ./...
      - run: go test -v -failfast ./...
